# Site
repository: yiwenc22/rs
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Yiwen Chen
title: Student
email: yiwenc0509@gmail.com
phone: (808)339-6861
website: https://yiwenc22.github.io/

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: Yiwenc22
github_username:  yiwenc22
linkedin_username: yiwen-chen-93687819a

# Additional icon links
additional_links:
- title: TechHui
  icon: fa-id-card
  url: http://www.techhui.com/profile/yiwenChen
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Mypictureme.jpg
about_content: | # this will include new lines to allow paragraphs
  Engaged, creative student studying for a Bachelor Of Science degree in the Department of Information and Computer
  Sciences at the University of Hawaii. I expect to graduate in Spring, 2022. Seeking to improve analytical skills,
  corroborate skills, and coding skills. Inquisitive, energetic computer science specialist skilled in leadership,
  with a strong foundation in math, logic, and cross-platform coding. Seeking to leverage solid skills in collaboration,
  communication, and development as a programmer.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Skills #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  <ul>
    <li>Java, JavaScript, C, C++<, SQL, JSP, HTML, CSS</li>
    <li>Exceptionally skilled at JavaScript</li>
    <li>Skilled in Illustrator, Mongo-DB</li>
    <li>Strong leadership, communication, and collaboration skills</li>
    <li>Skilled in critical thinking, logic, and basic math</li>
    <li>Cantonese, Mandarin, Englsih</li>
  </ul>

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
